<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\PhotoAIApp.Core\PhotoAIApp.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ImmichTagger.Server</AssemblyName>
    <RootNamespace>ImmichTagger.Server</RootNamespace>
  </PropertyGroup>
</Project>
