<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\PhotoAIApp.Core\PhotoAIApp.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.38</Version>
    <AssemblyVersion>0.1.38.0</AssemblyVersion>
    <FileVersion>0.1.38.0</FileVersion>
    <InformationalVersion>0.1.38-skip-immich-thumbs</InformationalVersion>
    <ApplicationIcon>Assets\PhotoAIApp.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
